services:
  api:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    env_file: .env
    restart: always
  db:
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: blockchain
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
